version: '3.8'

services:
  swapi:
    build: .
    container_name: swapi-api
    ports:
      - "8000:80"  # Map port 8000 on the host to port 80 in the container
    # environment:
    #   - SWAPI_URL=https://swapi.dev/api/
